Add UUID validation, and split installation ID into two lines

diff --git a/ember-satellite-projects/warcdealer/warcdealer b/ember-satellite-projects/warcdealer/warcdealer
--- a/ember-satellite-projects/warcdealer/warcdealer
+++ b/ember-satellite-projects/warcdealer/warcdealer
@@ -30,7 +30,7 @@ export warcdealerVersion='3.0'
 # echo "diskCheckInterval" >> ~/.warcdealer.cfg
 
 #6. As the user you chose in step 2, run the following command:
-# cd ~; mkdir 002F9DCE-F064-11E5-99AD-6BFA56EF8172; cd 002F9DCE-F064-11E5-99AD-6BFA56EF8172; git clone https://github.com/ethus3h/ember.git; cp ./ember/ember-satellite-projects/warcdealer/warcdealer ~/.warcdealer; chmod +x ~/.warcdealer; echo $(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)")-$(python -c 'import uuid; print str(uuid.uuid4())') >> ~/.warcdealer.cfg;
+# cd ~; mkdir 002F9DCE-F064-11E5-99AD-6BFA56EF8172; cd 002F9DCE-F064-11E5-99AD-6BFA56EF8172; git clone https://github.com/ethus3h/ember.git; cp ./ember/ember-satellite-projects/warcdealer/warcdealer ~/.warcdealer; chmod +x ~/.warcdealer; echo $(date +%Y-%m-%d-%H-%M-%S-%N)-$(xxd -pu <<< "$(date +%z)") >> ~/.warcdealer.cfg; echo $(python -c 'import uuid; print str(uuid.uuid4())') >> ~/.warcdealer.cfg;
 
 #Updating:
 
@@ -49,7 +49,13 @@ warcdealerUserName=$(sed '1q;d' "$HOME"/.warcdealer.cfg)
 warcdealerDiskThreshold=$(sed '2q;d' "$HOME"/.warcdealer.cfg)
 warcdealerDiskMonitorPartition=$(sed '3q;d' "$HOME"/.warcdealer.cfg)
 warcdealerDiskCheckInterval=$(sed '4q;d' "$HOME"/.warcdealer.cfg)
-warcdealerInstallationUUID=$(sed '5q;d' "$HOME"/.warcdealer.cfg)
+warcdealerInstallationUUID=$(sed '6q;d' "$HOME"/.warcdealer.cfg)
+
+warcdealerUUIDRegex='^[0-9A-F]{8}-[0-9A-F]{4}-[4][0-9A-F]{3}-[89AB][0-9A-F]{3}-[0-9A-F]{12}$'
+if [[ ! $warcdealerInstallationUUID =~ $warcdealerUUIDRegex ]]; then
+    echo "Invalid installation ID."
+    exit 1;
+fi
 
 while true; do
     left=$(df "$warcdealerDiskMonitorPartition" | grep / | sed -r 's/ +/ /g' | cut -f 4 -d ' ')
